name: Build & Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: 4.4

    - run: yarn

    - uses: sibiraj-s/action-eslint@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        eslint-args: '--ignore-path=.gitignore --quiet'
        extensions: 'js,ts'
        annotations: true

    - run: yarn run build

    - run: yarn run test

